# Generated by Django 4.2.18 on 2025-01-15 20:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='content',
            field=models.FileField(null=True, upload_to='files/%y', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', '.xlsx', '.xls'])]),
        ),
    ]
